version: '3'
services:

  #PHP Service
  app-acra-vite-vue:
    build:
      context: ./_docker/php-fpm
      dockerfile: Dockerfile
    container_name: app-acra-vite-vue
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app-acra-vite-vue
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./front/:/var/www
      - ${SSH_PATH}:/root/.ssh
    networks:
      - app-network
    extra_hosts:
      - "back.acra.local:${WEB_IP}"

  #PHP Service
  back-acra:
    build:
      context: ./_docker/php-fpm
      dockerfile: Dockerfile
    container_name: back-acra
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: back-acra
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./back/:/var/www
      - ${SSH_PATH}:/root/.ssh
    networks:
      - app-network

  #Nginx Service
  web-acra:
    image: nginx:alpine
    container_name: web-acra
    restart: unless-stopped
    tty: true
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./front/:/var/www/front
      - ./back/:/var/www/back
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./_docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      app-network:
        ipv4_address: ${WEB_IP}

  #MySQL Service
  db-acra:
    image: mysql:8.0
    container_name: db-acra
    restart: unless-stopped
    tty: true
    ports:
      - ${DOCKER_MAP_DB_PORT}:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: acra
      MYSQL_ROOT_PASSWORD: 123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    external: true

